// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";

import * as HomeRoute from "@/app/(home)/page.info";
import * as AboutRoute from "@/app/about/page.info";
import * as ContactRoute from "@/app/contact/page.info";
import * as EventsHlth2024Route from "@/app/events/hlth-2024/page.info";
import * as PrivacyRoute from "@/app/privacy/page.info";
import * as TermsRoute from "@/app/terms/page.info";

import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

export const Home = makeRoute("/(home)", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const About = makeRoute("/about", {
  ...defaultInfo,
  ...AboutRoute.Route,
});
export const Contact = makeRoute("/contact", {
  ...defaultInfo,
  ...ContactRoute.Route,
});
export const EventsHlth2024 = makeRoute("/events/hlth-2024", {
  ...defaultInfo,
  ...EventsHlth2024Route.Route,
});
export const Privacy = makeRoute("/privacy", {
  ...defaultInfo,
  ...PrivacyRoute.Route,
});
export const Terms = makeRoute("/terms", {
  ...defaultInfo,
  ...TermsRoute.Route,
});
