packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - aws-sdk
  - esbuild
  - prisma
  - sharp
