/// <reference path="sst-env.d.ts" />

import "sst";

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    IdentityPool: {
      id: string;
      type: "sst.aws.CognitoIdentityPool";
    };
    UserPool: {
      id: string;
      type: "sst.aws.CognitoUserPool";
    };
    UserPoolClient: {
      id: string;
      secret: string;
      type: "sst.aws.CognitoUserPoolClient";
    };
  }
}

export {};
