import {
  AdminSettings,
  AdminUsers,
  BeneficiariesAlignment,
  BeneficiariesAttribution,
  BeneficiariesSearch,
  FileStatus,
  FileUpload,
  Home,
  ManagePaymentBatches,
  ManagePaymentRates,
  NetworkEntities,
  NetworkEntity,
  NetworkPayer,
  NetworkPayers,
  NetworkPhysician,
  NetworkPhysicians,
  PaymentPlanning,
  QueuesCompleted,
  QueuesManage,
  QueuesWork,
  RecentShareNotifications,
  ShareFiles,
} from "@/routes";
import {
  ArrowUp,
  BarChartBig,
  Bell,
  BookHeart,
  Building,
  ClipboardCheck,
  ClipboardList,
  Cpu,
  Diff,
  DollarSign,
  File,
  HeartPulse,
  Hotel,
  Layers,
  LayoutDashboard,
  Network,
  Notebook,
  Pickaxe,
  Receipt,
  Search,
  Settings,
  Share,
  Stethoscope,
  Store,
  Users,
  Wrench,
} from "lucide-react";

import { SidebarNavItem } from "@workspace/ui/types/sidebar-nav-item";

export const MAIN_SIDEBAR_CONFIG = (slug?: string) =>
  [
    {
      id: "1",
      title: "Home",
      icon: LayoutDashboard,
      href: Home({}),
      allowedUserTypes: [
        "bpo",
        "payers",
        "payer",
        "po",
        "practice",
        "facility",
        "vendor",
        "physician",
      ],
    },
    {
      id: "2",
      title: "Files",
      icon: File,
      items: [
        {
          id: "2.1",
          title: "Status",
          icon: Cpu,
          href: FileStatus({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
        {
          id: "2.2",
          title: "Upload",
          icon: Diff,
          href: FileUpload({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
      ],
    },
    {
      id: "3",
      title: "Payment",
      icon: Receipt,
      items: [
        {
          id: "3.1",
          title: "Rates",
          icon: DollarSign,
          href: ManagePaymentRates({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
        {
          id: "3.2",
          title: "Planning",
          icon: Notebook,
          href: PaymentPlanning({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
        {
          id: "3.3",
          title: "Batches",
          icon: ArrowUp,
          href: ManagePaymentBatches({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
      ],
    },
    {
      id: "4",
      title: "Queues",
      icon: Layers,
      items: [
        {
          id: "4.1",
          title: "Manage",
          icon: BarChartBig,
          href: QueuesManage({}),
          allowedUserTypes: ["bpo"],
        },
        {
          id: "4.2",
          title: "Work",
          icon: Pickaxe,
          href: QueuesWork({}),
          allowedUserTypes: ["bpo"],
        },
        {
          id: "4.3",
          title: "Completed",
          icon: ClipboardCheck,
          href: QueuesCompleted({}),
          allowedUserTypes: ["bpo"],
        },
      ],
    },
    {
      id: "5",
      title: "Payer",
      icon: HeartPulse,
      href: NetworkPayer({ slug: slug || "" }),
      allowedUserTypes: ["payer"],
    },
    {
      id: "6",
      title: "Physician Org",
      icon: Building,
      href: NetworkEntity({ slug: slug || "" }),
      allowedUserTypes: ["po"],
    },
    {
      id: "7",
      title: "Practice",
      icon: Building,
      href: NetworkEntity({ slug: slug || "" }),
      allowedUserTypes: ["practice"],
    },
    {
      id: "8",
      title: "Facility",
      icon: Hotel,
      href: NetworkEntity({ slug: slug || "" }),
      allowedUserTypes: ["facility"],
    },
    {
      id: "9",
      title: "Vendor",
      icon: Store,
      href: NetworkEntity({ slug: slug || "" }),
      allowedUserTypes: ["vendor"],
    },
    {
      id: "10",
      title: "Physician",
      icon: Stethoscope,
      href: NetworkPhysician({ slug: slug || "" }),
      allowedUserTypes: ["physician"],
    },
    {
      id: "11",
      title: "Network",
      icon: Network,
      items: [
        {
          id: "11.1",
          title: "Payers",
          icon: HeartPulse,
          href: NetworkPayers({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
        {
          id: "11.2",
          title: "Network Entities",
          icon: Building,
          href: NetworkEntities({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
        {
          id: "11.3",
          title: "Physicians",
          icon: Stethoscope,
          href: NetworkPhysicians({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
      ],
    },
    {
      id: "12",
      title: "Beneficiaries",
      icon: Users,
      items: [
        {
          id: "12.1",
          title: "Search",
          icon: Search,
          href: BeneficiariesSearch({}),
          allowedUserTypes: ["bpo", "payers", "payer"],
        },
        {
          id: "12.2",
          title: "Alignment",
          icon: BookHeart,
          href: BeneficiariesAlignment({}),
          allowedUserTypes: ["bpo", "payers", "payer", "physician"],
        },
        {
          id: "12.3",
          title: "Attribution",
          icon: ClipboardList,
          href: BeneficiariesAttribution({}),
          allowedUserTypes: ["bpo", "payers", "payer", "physician"],
        },
      ],
    },
    {
      id: "13",
      title: "Share",
      icon: Share,
      items: [
        {
          id: "13.1",
          title: "Files",
          icon: File,
          href: ShareFiles({}),
          allowedUserTypes: [
            "bpo",
            "payers",
            "payer",
            "po",
            "practice",
            "facility",
            "vendor",
            "physician",
          ],
          requiredRoles: ["read-files", "write-files"],
        },
        {
          id: "13.2",
          title: "Notifications",
          icon: Bell,
          href: RecentShareNotifications({}),
          allowedUserTypes: [
            "bpo",
            "payers",
            "payer",
            "po",
            "practice",
            "facility",
            "vendor",
            "physician",
          ],
          requiredRoles: ["read-notifications", "write-notifications"],
        },
      ],
    },
    {
      id: "14",
      title: "Admin",
      icon: Wrench,
      items: [
        {
          id: "14.1",
          title: "Settings",
          icon: Settings,
          href: AdminSettings({}),
          isAdminOnly: true,
        },
        {
          id: "14.2",
          title: "Users",
          icon: Users,
          href: AdminUsers({}),
          isAdminOnly: true,
        },
      ],
    },
  ] satisfies SidebarNavItem[];
