import { ComboItem } from "@workspace/ui/types/combo-item";

export const NPPES_STATES: ComboItem[] = [
  { label: "Alaska", value: "ak" },
  { label: "Alabama", value: "al" },
  { label: "Arkansas", value: "ar" },
  { label: "American Samoa", value: "as" },
  { label: "Arizona", value: "az" },
  { label: "California", value: "ca" },
  { label: "Colorado", value: "co" },
  { label: "Connecticut", value: "ct" },
  { label: "District of Columbia", value: "dc" },
  { label: "Delaware", value: "de" },
  { label: "Florida", value: "fl" },
  { label: "Georgia", value: "ga" },
  { label: "Guam", value: "gu" },
  { label: "Hawaii", value: "hi" },
  { label: "Iowa", value: "ia" },
  { label: "Idaho", value: "id" },
  { label: "Illinois", value: "il" },
  { label: "Indiana", value: "in" },
  { label: "Kansas", value: "ks" },
  { label: "Kentucky", value: "ky" },
  { label: "Louisiana", value: "la" },
  { label: "Massachusetts", value: "ma" },
  { label: "Maryland", value: "md" },
  { label: "Maine", value: "me" },
  { label: "Marshall Islands", value: "mh" },
  { label: "Michigan", value: "mi" },
  { label: "Minnesota", value: "mn" },
  { label: "Missouri", value: "mo" },
  { label: "Northern Mariana Islands", value: "mp" },
  { label: "Mississippi", value: "ms" },
  { label: "Montana", value: "mt" },
  { label: "North Carolina", value: "nc" },
  { label: "North Dakota", value: "nd" },
  { label: "Nebraska", value: "ne" },
  { label: "New Hampshire", value: "nh" },
  { label: "New Jersey", value: "nj" },
  { label: "New Mexico", value: "nm" },
  { label: "Nevada", value: "nv" },
  { label: "New York", value: "ny" },
  { label: "Ohio", value: "oh" },
  { label: "Oklahoma", value: "ok" },
  { label: "Oregon", value: "or" },
  { label: "Pennsylvania", value: "pa" },
  { label: "Puerto Rico", value: "pr" },
  { label: "Palau", value: "pw" },
  { label: "Rhode Island", value: "ri" },
  { label: "South Carolina", value: "sc" },
  { label: "South Dakota", value: "sd" },
  { label: "Tennessee", value: "tn" },
  { label: "Texas", value: "tx" },
  { label: "Utah", value: "ut" },
  { label: "Virginia", value: "va" },
  { label: "Virgin Islands", value: "vi" },
  { label: "Vermont", value: "vt" },
  { label: "Washington", value: "wa" },
  { label: "Wisconsin", value: "wi" },
  { label: "West Virginia", value: "wv" },
  { label: "Wyoming", value: "wy" },
  { label: "Foreign Country", value: "zz" },
];
