// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod/v4";

import * as AdminClientsRoute from "@/app/(authed)/admin/clients/page.info";
import * as AdminHealthPlansRoute from "@/app/(authed)/admin/plans/page.info";
import * as AdminUsersRoute from "@/app/(authed)/admin/users/page.info";
import * as AgentRoute from "@/app/(authed)/agent/page.info";
import * as HomeRoute from "@/app/(authed)/page.info";
import * as RateLimitRoute from "@/app/(authed)/rate-limit/page.info";
import * as CallLogRoute from "@/app/(authed)/reporting/call-log/page.info";
import * as DashboardRoute from "@/app/(authed)/reporting/dashboard/page.info";
import * as SignInRoute from "@/app/sign-in/[[...sign-in]]/page.info";

import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

export const Home = makeRoute("/(authed)", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const AdminClients = makeRoute("/(authed)/admin/clients", {
  ...defaultInfo,
  ...AdminClientsRoute.Route,
});
export const AdminHealthPlans = makeRoute("/(authed)/admin/plans", {
  ...defaultInfo,
  ...AdminHealthPlansRoute.Route,
});
export const AdminUsers = makeRoute("/(authed)/admin/users", {
  ...defaultInfo,
  ...AdminUsersRoute.Route,
});
export const Agent = makeRoute("/(authed)/agent", {
  ...defaultInfo,
  ...AgentRoute.Route,
});
export const RateLimit = makeRoute("/(authed)/rate-limit", {
  ...defaultInfo,
  ...RateLimitRoute.Route,
});
export const CallLog = makeRoute("/(authed)/reporting/call-log", {
  ...defaultInfo,
  ...CallLogRoute.Route,
});
export const Dashboard = makeRoute("/(authed)/reporting/dashboard", {
  ...defaultInfo,
  ...DashboardRoute.Route,
});
export const SignIn = makeRoute("/sign-in/[[...sign-in]]", {
  ...defaultInfo,
  ...SignInRoute.Route,
});
