// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";

import * as AdminSettingsRoute from "@/app/(authed)/admin/settings/page.info";
import * as AdminUsersRoute from "@/app/(authed)/admin/users/page.info";
import * as BeneficiariesAlignmentRoute from "@/app/(authed)/beneficiaries/alignment/page.info";
import * as BeneficiariesAttributionRoute from "@/app/(authed)/beneficiaries/attribution/page.info";
import * as BeneficiariesSearchRoute from "@/app/(authed)/beneficiaries/search/page.info";
import * as BeneficiaryRoute from "@/app/(authed)/beneficiary/[slug]/page.info";
import * as FileStatusRoute from "@/app/(authed)/file/status/page.info";
import * as FileUploadRoute from "@/app/(authed)/file/upload/page.info";
import * as NetworkEntitiesRoute from "@/app/(authed)/network/entities/page.info";
import * as NetworkEntityRoute from "@/app/(authed)/network/entity/[slug]/page.info";
import * as NetworkPayerRoute from "@/app/(authed)/network/payer/[slug]/page.info";
import * as NetworkPayersRoute from "@/app/(authed)/network/payers/page.info";
import * as NetworkPhysicianRoute from "@/app/(authed)/network/physician/[slug]/page.info";
import * as NetworkPhysiciansRoute from "@/app/(authed)/network/physicians/page.info";
import * as HomeRoute from "@/app/(authed)/page.info";
import * as PaymentsCapitationRoute from "@/app/(authed)/payments/capitation/page.info";
import * as PaymentsClaimsRoute from "@/app/(authed)/payments/claims/page.info";
import * as PaymentsPerformanceRoute from "@/app/(authed)/payments/performance/page.info";
import * as QueuesCompletedRoute from "@/app/(authed)/queues/completed/page.info";
import * as QueuesManageRoute from "@/app/(authed)/queues/manage/page.info";
import * as QueuesWorkRoute from "@/app/(authed)/queues/work/page.info";
import * as RateLimitRoute from "@/app/(authed)/rate-limit/page.info";
import * as SetupRoute from "@/app/(authed)/setup/page.info";
import * as ShareFilesRoute from "@/app/(authed)/share/files/page.info";
import * as ShareNotificationDetailRoute from "@/app/(authed)/share/notifications/[slug]/page.info";
import * as RecentShareNotificationsRoute from "@/app/(authed)/share/notifications/recent/page.info";
import * as SignInRoute from "@/app/sign-in/[[...sign-in]]/page.info";

import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

export const Home = makeRoute("/(authed)", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const AdminSettings = makeRoute("/(authed)/admin/settings", {
  ...defaultInfo,
  ...AdminSettingsRoute.Route,
});
export const AdminUsers = makeRoute("/(authed)/admin/users", {
  ...defaultInfo,
  ...AdminUsersRoute.Route,
});
export const BeneficiariesAlignment = makeRoute(
  "/(authed)/beneficiaries/alignment",
  {
    ...defaultInfo,
    ...BeneficiariesAlignmentRoute.Route,
  },
);
export const BeneficiariesAttribution = makeRoute(
  "/(authed)/beneficiaries/attribution",
  {
    ...defaultInfo,
    ...BeneficiariesAttributionRoute.Route,
  },
);
export const BeneficiariesSearch = makeRoute("/(authed)/beneficiaries/search", {
  ...defaultInfo,
  ...BeneficiariesSearchRoute.Route,
});
export const Beneficiary = makeRoute("/(authed)/beneficiary/[slug]", {
  ...defaultInfo,
  ...BeneficiaryRoute.Route,
});
export const FileStatus = makeRoute("/(authed)/file/status", {
  ...defaultInfo,
  ...FileStatusRoute.Route,
});
export const FileUpload = makeRoute("/(authed)/file/upload", {
  ...defaultInfo,
  ...FileUploadRoute.Route,
});
export const NetworkEntities = makeRoute("/(authed)/network/entities", {
  ...defaultInfo,
  ...NetworkEntitiesRoute.Route,
});
export const NetworkEntity = makeRoute("/(authed)/network/entity/[slug]", {
  ...defaultInfo,
  ...NetworkEntityRoute.Route,
});
export const NetworkPayer = makeRoute("/(authed)/network/payer/[slug]", {
  ...defaultInfo,
  ...NetworkPayerRoute.Route,
});
export const NetworkPayers = makeRoute("/(authed)/network/payers", {
  ...defaultInfo,
  ...NetworkPayersRoute.Route,
});
export const NetworkPhysician = makeRoute(
  "/(authed)/network/physician/[slug]",
  {
    ...defaultInfo,
    ...NetworkPhysicianRoute.Route,
  },
);
export const NetworkPhysicians = makeRoute("/(authed)/network/physicians", {
  ...defaultInfo,
  ...NetworkPhysiciansRoute.Route,
});
export const PaymentsCapitation = makeRoute("/(authed)/payments/capitation", {
  ...defaultInfo,
  ...PaymentsCapitationRoute.Route,
});
export const PaymentsClaims = makeRoute("/(authed)/payments/claims", {
  ...defaultInfo,
  ...PaymentsClaimsRoute.Route,
});
export const PaymentsPerformance = makeRoute("/(authed)/payments/performance", {
  ...defaultInfo,
  ...PaymentsPerformanceRoute.Route,
});
export const QueuesCompleted = makeRoute("/(authed)/queues/completed", {
  ...defaultInfo,
  ...QueuesCompletedRoute.Route,
});
export const QueuesManage = makeRoute("/(authed)/queues/manage", {
  ...defaultInfo,
  ...QueuesManageRoute.Route,
});
export const QueuesWork = makeRoute("/(authed)/queues/work", {
  ...defaultInfo,
  ...QueuesWorkRoute.Route,
});
export const RateLimit = makeRoute("/(authed)/rate-limit", {
  ...defaultInfo,
  ...RateLimitRoute.Route,
});
export const Setup = makeRoute("/(authed)/setup", {
  ...defaultInfo,
  ...SetupRoute.Route,
});
export const ShareFiles = makeRoute("/(authed)/share/files", {
  ...defaultInfo,
  ...ShareFilesRoute.Route,
});
export const ShareNotificationDetail = makeRoute(
  "/(authed)/share/notifications/[slug]",
  {
    ...defaultInfo,
    ...ShareNotificationDetailRoute.Route,
  },
);
export const RecentShareNotifications = makeRoute(
  "/(authed)/share/notifications/recent",
  {
    ...defaultInfo,
    ...RecentShareNotificationsRoute.Route,
  },
);
export const SignIn = makeRoute("/sign-in/[[...sign-in]]", {
  ...defaultInfo,
  ...SignInRoute.Route,
});
