export type PayloadProcessingAccountCreatedResponse = {
  plugin_id: string;
  type: "account_created";
  account: {
    attrs: string | null;
    billing_contact: {
      city: string;
      email: string;
      name: string;
      phone: string;
      postal_code: string;
      state_province: string;
      street_address1: string;
      street_address2: string | null;
      website: string;
    };
    created_at: string;
    description: string | null;
    id: string;
    industry: string;
    legal_entity: string | null;
    legal_entity_id: string;
    modified_at: string;
    name: string;
    object: "processing_account";
    parent_org_id: string;
    payment_methods: {
      id: string;
      object: "payment_method";
      account_holder: string;
      attrs: string | null;
      bank_account: {
        account_class: "business" | string;
        account_currency: string;
        account_number: string;
        account_type: string;
        routing_number: string;
      };
      bank_name: string;
      billing_address: {
        city: string | null;
        country_code: string;
        postal_code: string | null;
        state_province: string | null;
        street_address: string | null;
      };
      created_at: string;
      customer_id: string;
      default_credit_method: boolean;
      default_deposit_method: boolean;
      default_payment_method: boolean;
      default_reversal_method: boolean | null;
      description: string;
      email: string | null;
      keep_active: boolean;
      modified_at: string;
      phone_number: string | null;
      status: string;
      transfer_type: string;
      type: string;
      verification_status: string;
    }[];
    processing_settings: {
      account_id: string;
      amex_trans_cost: number | null;
      amex_trans_rate: number | null;
      applepay_enabled: boolean;
      attrs: null;
      bank_account: {
        features: {
          ach_verify: { enabled: boolean };
          enhanced_account_verify: { enabled: boolean };
        };
      };
      bank_account_conv_fee_alloc: number;
      bank_account_processing_enabled: boolean;
      bank_account_trans_cost: number;
      bank_account_trans_rate: number;
      batch_fee: number;
      billing_flow: string;
      billing_preference: string;
      billing_setup: string;
      card: null;
      card_present: boolean;
      card_processing: {
        credit: number;
        debit: number;
        prepaid: number;
      };
      card_processing_enabled: boolean;
      change_fee: number;
      chargeback_fee: number;
      created_at: string;
      credit_conv_fee_alloc: number | null;
      credit_trans_cost: number | null;
      credit_trans_rate: number | null;
      currency: string;
      debit_conv_fee_alloc: number | null;
      debit_trans_cost: number | null;
      debit_trans_rate: number | null;
      description: string | null;
      duplicate_trans_limit: string;
      ecommerce: boolean;
      funding: {
        default_descriptor: string | null;
        delay: number;
        style: string;
      };
      googlepay_enabled: boolean;
      googlepay_merchant_id: string | null;
      guarantor_required: boolean;
      id: string;
      integration_type: string;
      is_template: boolean | null;
      minimum_bill: number;
      modified_at: string;
      monthly_processing_fee: number | null;
      nabu_fee: number;
      object: "processing_setting";
      pci_fee: number;
      prepaid_conv_fee_alloc: number | null;
      prepaid_trans_cost: number | null;
      prepaid_trans_rate: number | null;
      pricing: "flat_rate" | string;
      processing_type: "payfac" | string;
      reject_fee: number | null;
      retrieval_fee: number;
      trans_limit: number;
    };
    processing_settings_id: string;
    status: string;
  };
};
