---
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vbtech
      MYSQL_DATABASE: vbtech
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - .mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
